### ISSUE TITLE
Beginning the consent

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#10]
This issues is discussed already, but I now have a sample screen shot of this step attached.

Basically, when the person is eligible and they get their Check mark, should have two options to start the consent.

Red box should be around "Go to consent" text.

![go to consent](https://cloud.githubusercontent.com/assets/13530341/9328964/5f5f045e-457b-11e5-8123-951252acf4e3.jpg)

**Comment by fastharper** [comment]
merged both Tasks (qualification and consent) into a single task and removed the middle "You Are Eligible" screen.
