### ISSUE TITLE
Yale/placenta app icon "Y" needs adjusted right

### ISSUE THREAD

**Issue by fastharper** [estimated-placental-volume/EPVRK#3]
<img width="250" alt="iconissue" src="https://cloud.githubusercontent.com/assets/5182797/9295353/d8928cf2-4430-11e5-9fee-16a47d257d67.png">

the serif of the Y on the left is too close to the edge

**Comment by harveykliman** [comment]
I just emailed Matt an updated version with Y moved to right, its left edge lining up with left edge of blue triangle.
