### ISSUE TITLE
Need App Store materials

### ISSUE THREAD

**Issue by fastharper** [estimated-placental-volume/EPVRK#31]
Description
Screen shots - every iPhone size (4, 5, 6, 6+)
Support URL
Contact info
Keywords (for searching)

**Comment by harveykliman** [comment]
Description:
https://www.dropbox.com/s/ey6vagk08p4xzdu/EPV%20RK%20description%20v1%2023Aug15.docx?dl=0

Screen shots: I can only do it for the 6. Do you want me to do it or can you in your simulator?

Support URL:
http://klimanlabs.yale.edu/placenta/epv/

Contact infö:
Harvey J. Kliman, MD, PhD
Kliman Laboratories
Reproductive and Placental Research Unit
Department of Obstetrics, Gynecology and Reproductive Sciences
Yale University School of Medicine
333 Cedar Street
New Haven, Connecticut  06520-8063

Keywords:
Placenta
Pregnancy
Fetus
Obstetrics
Ultrasound
Baby

**Comment by harveykliman** [comment]
Matt: will you be able to get the screen shots from your simulator?

**Comment by harveykliman** [comment]
Here are the 6s screen shots as pngs:

https://www.dropbox.com/sh/1vtzu5e08kubpq4/AAAocSS5xrYhZWxs4OrTM8WMa?dl=0
