### ISSUE TITLE
Terms of service

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#45]
Text pending, but we'll need a new item to click on the bottom below the "View Consent Form"

**Comment by harveykliman** [comment]
Here is the text we need to include in the sign up process:

https://www.dropbox.com/s/7bwq5ee5333ttpt/End%20User%20Terms%20of%20Use%20Template%2C%20App%20Kliman%20EPV.docx?dl=0

I suggest the following:
1. after they Agree to the consent a pop up appears asking them to confirm they have read the consent. They then Agree or Cancel.
2. Right after that a new page appears what the title:

End User License Agreement

with the text from the above link.

Again, they can Cancel or Agree. If they agree, they continue. If they Cancel, they are not allowed to enter the app.

If they agree they go to the signature page as before.

**Comment by fastharper** [comment]
done - inserted as the final section to the consent document
