### ISSUE TITLE
Ultrasound instruction edits

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#50]
Page 1:

I've been asked to remove the graph on page one because it "may reveal clinical information."

Please use this image on page 1:

https://www.dropbox.com/s/m5xw98pe3a3uad7/01-GA%20v%20EPV%20no%20lines.png?dl=0

Page 8:

Once %ile is gone from data entry page I'll make an image for this.

Page 9:

New image:

https://www.dropbox.com/s/tvohh774eiubo9k/09-EPV%20graph%20no%20lines.png?dl=0

**Comment by fastharper** [comment]
Page 1: Done
Page 9: Done

**Comment by fastharper** [comment]
page 8: done
