### ISSUE TITLE
Signature entry page issue

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#57]
When I use my 6s and enter my first and last name the Next button is blocked:

![img_8444](https://cloud.githubusercontent.com/assets/13530341/10121101/b820d86c-64aa-11e5-8399-2c1c66f24f0a.jpg)

Can you have the page move up when you are in the Last name field so the Next is visible?

**Comment by fastharper** [comment]
This is a ResearchKit issue, possibly a bug. Not sure.
