### ISSUE TITLE
New schema

### ISSUE THREAD

**Issue by fastharper** [estimated-placental-volume/EPVRK#58]
Profile:

{
"id": "75dc73ac-db7e-436a-b633-666e0fca7e2c",
"height": 4.54
"weight": 3.27
"dob": 49510932,
"latitude": 41.8,
"longitude": 87.7,
"outcome": {  // optional
   "id": "85dc73ac-db7e-436a-b633-666e0fca7e2c",
   "date": 49510932, // optional
   "birth_weight": 327, // optional
   "gender": 1, // optional, 0=male, 1=female, 2=other
   "apgar1": 7, // optional, 0 to 10
   "apgar5": 8, // optional, 0 to 10
   "clinical_conditions": [1, 3]  // optional, array of Int, values from 0 to 4
   }
}

**Comment by fastharper** [comment]
New: "outcome" is new. It's optional. All the fields in Outcome (except the id) are optional, and may be missing from the JSON if the user doesn't supply them.

Height or weight is new. Can't remember which. They are optional in the sense the user may not supply them, but they are always in the JSON - will be 0 if the user does not supply.

**Comment by fastharper** [comment]
```
    static let mother_weight = "mother_weight"
    static let mother_bp_systolic = "mother_bp_systolic"
    static let mother_bp_diastolic = "mother_bp_diastolic"
```

**Comment by fastharper** [comment]
int

**Comment by icksa** [comment]
All done
