### ISSUE TITLE
Final survey and Skip this question

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#59]
If you select:

Skip this question

on the final survey:

![pregnancy outcomes](https://cloud.githubusercontent.com/assets/13530341/10123637/820cf938-650c-11e5-8d71-3d918d5e5f11.jpg)

the app just quits.

I suspect this will be fixed when you create the final Thank You page.

**Comment by fastharper** [comment]
yeah, it's a bug, already fixed. Look for build 12.

**Comment by harveykliman** [comment]
Great. Can we talk about the final Thank you page? If possible we will need two kinds of pages based on their responses: one for a healthy baby, one for a loss or problem outcome. Can you have a branch based on the answers?
