### ISSUE TITLE
Consent share email no subject

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#62]
When you email the consent an email is created, but there is no subject:

![consent email](https://cloud.githubusercontent.com/assets/13530341/10127662/c80dc0e0-6573-11e5-8ffc-438e661b6042.jpg)

Can you populate the Subject field with:

EPV Consent

**Comment by fastharper** [comment]
this is by design - we are using the Action button, by which the user may share in any number of ways.
