### ISSUE TITLE
Signature page text needs editing

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#64]
Please update the text on the signature page:
![img_8659](https://cloud.githubusercontent.com/assets/13530341/10154652/347355a0-6638-11e5-97ff-b0cb92977366.jpg)

to read:

Your name is used only to sign this Consent Document, which is kept as a PDF on your phone. Your name is not sent to the investigators or shared with anyone. You do not give up any of your legal rights by signing this Consent.

**Comment by fastharper** [comment]
fixed in build 14, whenever that is.
