### ISSUE TITLE
Ultrasound Instructions

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#7]
"View Manual" section now updated to "Ultrasound Instructions". Also, png images uploaded to Dropbox for app.

All Ultrasound Instructions png images are here:
https://www.dropbox.com/sh/j6bea7gcij4pmzg/AAC0CFZzefqIU1qnhnrxcEVaa?dl=0

Here is the Word document with the text:
https://www.dropbox.com/s/a707geom40qrbrj/EPV%20RK%20manual%20v3%2022Aug15.docx?dl=0

**Comment by fastharper** [comment]
please added the order/index to the file name
also each step/screen can have a title
